# Model
MODEL_DIR: "EleutherAI/pythia-70m"
ACTS_LAYER: 5
EMBEDDING_DIM: 512

# Encoder Size
PROJECTION_FACTOR: 1

# Save Paths
PROMPT_IDS_PATH: "acts_data/activations_prompt_ids.npy"
ACTS_DATA_PATH: "acts_data/activations_dataset.pt"
ENCODER_PATH: "acts_data/learned_encoder.pt"

# Reproducibility
SEED: 0
