# Model
MODEL_DIR: "EleutherAI/pythia-70m"
ACTS_LAYER: 2

# Encoder Size
PROJECTION_FACTOR: 10

# Save Paths
PROMPT_IDS_PATH: "acts_data/activations_prompt_ids.npy"
ACTS_DATA_PATH: "acts_data/activations_dataset.pt"
ENCODER_PATH: "acts_data/learned_encoder.pt"
BIASES_PATH: "acts_data/learned_biases.pt"
TOP_K_INFO_PATH: "acts_data/token_info.csv"

# Autoencoder Training
LAMBDA_L1: 1e-2
LEARNING_RATE: 1e-2
NUM_WORKERS: 4

# Reproducibility
SEED: 0
